"""ingestion: jobs, watched_folders, ingested_originals + documents.origin_original_id

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-15 21:52:38.589471

Cria o substrato de schema da Fase 2 (D-02/D-09/PROC-02/PROC-03):
- `watched_folders` (pastas monitoradas) — antes de `ingested_originals` (FK)
- `ingested_originals` (gate de dedup por `original_hash` único)
- `jobs` (fila durável; UniqueConstraint `uq_jobs_hash_step` = idempotência)
- `documents.origin_original_id` (FK nullable → ingested_originals)

CAVEAT do trigger (WR-05): o `batch_alter_table('documents')` recria a tabela
`documents` no modo batch do SQLite, o que DERRUBA o trigger `trg_documents_updated_at`
criado em 0001. Recriamos o trigger ao final do `upgrade()` (SQLite) e garantimos
seu estado correto no `downgrade()`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# DDL do trigger de updated_at (idêntico a 0001) — reutilizado aqui porque o
# batch recreate de `documents` o descarta.
_TRG_DROP = "DROP TRIGGER IF EXISTS trg_documents_updated_at"
_TRG_CREATE = (
    "CREATE TRIGGER trg_documents_updated_at "
    "AFTER UPDATE ON documents FOR EACH ROW BEGIN "
    "UPDATE documents SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id; "
    "END"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ordem respeita FKs: watched_folders antes de ingested_originals; e a coluna
    # em documents só após ingested_originals existir.
    op.create_table('watched_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('pages_per_block', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watched_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watched_folders_path'), ['path'], unique=True)

    op.create_table('ingested_originals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_hash', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('source_folder_id', sa.Integer(), nullable=True),
    sa.Column('block_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicate_hits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_folder_id'], ['watched_folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingested_originals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingested_originals_original_hash'), ['original_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_ingested_originals_source_folder_id'), ['source_folder_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_hash', sa.String(length=64), nullable=False),
    sa.Column('step', sa.String(), server_default='ingest', nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    # CHECK (status IN (...)) renderizado inline (igual ao state de documents em 0001).
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='ck_jobs_status', native_enum=False, create_constraint=True, length=10), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_hash', 'step', name='uq_jobs_hash_step')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_original_hash'), ['original_hash'], unique=False)

    # Coluna de vínculo bloco→original. O batch recreate de `documents` derruba o
    # trigger trg_documents_updated_at — recriado logo abaixo.
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_original_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_origin_original_id'), ['origin_original_id'], unique=False)
        batch_op.create_foreign_key('fk_documents_origin_original_id', 'ingested_originals', ['origin_original_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###

    # WR-05: recriar o trigger de updated_at descartado pelo batch recreate de
    # `documents` acima (SQLite).
    if op.get_bind().dialect.name == "sqlite":
        op.execute(_TRG_DROP)
        op.execute(_TRG_CREATE)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover a coluna/FK de documents (batch recreate derruba o trigger de novo).
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documents_origin_original_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_origin_original_id'))
        batch_op.drop_column('origin_original_id')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_original_hash'))
        batch_op.drop_index(batch_op.f('ix_jobs_next_run_at'))

    op.drop_table('jobs')

    with op.batch_alter_table('ingested_originals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingested_originals_source_folder_id'))
        batch_op.drop_index(batch_op.f('ix_ingested_originals_original_hash'))

    op.drop_table('ingested_originals')

    with op.batch_alter_table('watched_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watched_folders_path'))

    op.drop_table('watched_folders')
    # ### end Alembic commands ###

    # WR-05: o batch recreate de `documents` no início do downgrade descartou o
    # trigger — restaurá-lo para o estado da Fase 1 (0001).
    if op.get_bind().dialect.name == "sqlite":
        op.execute(_TRG_DROP)
        op.execute(_TRG_CREATE)
